sudo: false
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: jcX8V+I8FMZs6j/LPe0SGsp/RkwMK9uDyKp2XhcV2YQa678p5L4rR7YX8Ewi3kNNbrKeVVXsiHTrdmgFmqt0rcqMwXacrQYTa9FJTWyvOuv1BdjLZf484HNmLLGVH8lGo1cep3VVGp/EiTwLwq66QawjPqcx3iPzCxEh2hNaKbGOeV5d7JXyhaTz5MpbnCpYAUHO1fAe7L3VF6yWDOS3Yv40Na5uozWZUs4mm3FOD6029VwBqlnUzxbyLzwUvVrHqbq4AYFdWOSlRpOZT/SDRavwQEzkWVnMODbbA8TjAThgEGQXad+RwOo09UoqrRyTWgEhLBjzUEsYfMlPozd5n5Y01h9KE108YgyCFf+7nyHiuUUPsWVm5ywUZiV/Wnz9csT54FqyGj6wcj9fV/L4eVqTfKvfHXQmXo97ucVaW/q+GPDnKFQ/KIkl189YeLslJvKUnSuKnJSuLa5tam4Fi7hvmz+5a5JIc+Eb5CcCo0hhJVqwaru2bSi1GmM0dLk5G5c9mkoLHPfrA5+W6KbVmYvXXDNETX8b04e5nkNktEc462RJpXueQnCHWHllUtNTgmTt6EGqlWSNv2mUWtZU7pe3Tynw155/plYHJhV9/yuDR7nMR5wKW0e+4uvsE0t6I/o8puJzwyYVo8nGwwIScfC6eE8LIW0Gxc0rcppVli0=
  - secure: ONd3ktFDksSb4D3/VZ7M2/LwDZKdmLK6ZggdZSJQAZaFRI9XSR+wb/1iJwnniViO1vuEmBrr+FD1PsV+C+hLZJVevRg7SYYStSRzXLw4B4rsThCErUuGD1vVeQ0t9aYakCQSEKssijMpKu+yRIAE6jA+31OmqG0hWYmwON2aNMYk5plU6Wm5fOetp/P7BETRDifpWWvZqW4LQcTBMnLRPRxmgxXBW67CaxGGhgUaqSp/sVSF85PungzitYbfuC9/4VFTDSaP0pRZq8i4mjLeto6w+WK1ndz77Wz/s61Seqsh/ZInqXwIF5Z8NBZK+fUInwq5tninz0qXV4zpL0V4VbctwBSLIdn8nboncNVuB5tMfD/O++5MdeO+DNeg3rn9Fd/nT8Z52n8qckeTzTAq9t2+f+f5xjjPpz25Ex2UAvk+5ivyETCLgWRL1z4wSIAUqPdyR1L2DwUIy6p3IZPgCTx3kOkpXpW/ELlgvuf+JL477O7SUQoB42ysckNaVhBKnQYRSXsW6j9yepV5x7YbAz6bxI9vlqP4KeblrHmKEjirYy38fcZ4k7t1ajd2q3eU1INxcXor0rrAOzgFMvEv3JSDc9xCkoWSKSv9zff+ZMyZVPJucri7zfNSqZhrZLH7lzTMmHIGuUWHWcDRyzymgziKTE9N4vb3YvqMWeKHXpg=
  - secure: PAesjc9gDp0wRNwUMiWgzs0OhG7yQZd7Ldg6S9gbrCt04jdPYceqxUG0Dx3bbCUD9AwzakLQTyFcPUv3KkfxA6crAHbUVr+jbcSuLDbOjyllKKHJT0v5LWgQlixZFTpHFwAR5xdq/IUeF4GPJnJ17b43Q234hC0bhaQ7jTw96YgXyX/EJzLRNNlxiHKqlza9XuEbnpPy9PwZ97PV+f7XrJ+QW5E87vEMkUsnpusz9WbLqkfbiAD0ccGi4+jBizm1AgAGyPrdn8r+oEIowQY/8zAYT+16Gitv4MP0M2pqJ2s4yEUZG+HaFljpmM1SIOPPV18BzabZFc2lpo5qWAIYmGrD9jico6TpNFOFsgM0FfZbUnjsT3FRvh4r/X2yZSXmwTHzj7QuhxGJQWpat/oexiKNAnjNg6KV6bWEIz24yod7b0/E4TUyM4zFtoO8eM/KYJ4mlhpbJVn+Xx05w0uAzKkeq7e/Q+xqG9Pp1/HxsWHNhzNTLF3M4JGVa8DRnS2Kt8wntGcI6BQN5SbcHwvqR5iGRMRNL9NwT7q8maNf0HA/rc0zMbYXq/X/BBU6YMptwEtPEw5Hq0FQhdXQQRfBFcgCF94hau57Bsc+hfgq4ibNnxAZ4Z0ajQZOOgR/YL82+LuKh4+knqRwjhpKPAm2o4ZL7uOJqSx7Fgms8BAbkuc=
  - secure: CTU0pkRDzGe8SAwNJ0hbaZVJRkqRd2IvSoAmJUKheZLe3DxDvJ/rwS8uNJso4qg99wfZW45zM0qdK8n6avfsz0TiH4dEcCZQpW+vTsUSxC8+dMP3QvT/bsshL1homgiRk7B1P9Th0c0lP66d7HN08bQRsf9AGkkat9msRKtdnYL51B/+S96qI5ghOA8WiYvABV+LCdKk/yiSldkCSHZgjyj9UyK/HldhupxYscv/kh8kB8mwmaeRpi7VgylckytRJJmHLJSvKp+vO5BjTa4nU3H8Qrijo5ugudTwv7uyunl5qQtXMKXEn8ugaQOyBAQ70sZTV0iWz9Q3HFnxRozP9eXjfjxcMa3H4Phm65wVb6v/nJbwcz0pYM8Hk2W0KIcJ+ZcGxR8vOh9yH4LuXUXSzVfD8pUN94Ti6DcfOQprU6EQE+2v0E4EamCo0Gyl64pbVsdJdaI8d0GPezw/vtnRpKlqP4eJrdqYauxPNa+dMdKdJSo28z+qk0/KJ+DMOvtd+H9XnG7UWBNWGJkapCT55iLr6/1+z4o1rMPkKjwRZoMsic+Hg29FXwRnjz/K86wD1dQjd3JL6q3ofUSNiDPPyK7MgImw8XVIipOzxH4M/o22bGrbNpQDVMxKJTCuCFUsBaWF/Ec0JrNkCg65+hmEVJgmOPQGL/znJO+McwI+EY4=
