sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: WsDyqGGOmpFkJGvFsN1SJthXJzXPWKXbMYrM6YoXg16b1+qLqlUWhkLVbOVhJk3nnYCw9qmaEHf5jxjrWdGuHFfJ4NYAISjJmqokmOkroNN/KW/suQJiqTzpWfIkyJwFmiJypg1Im4tb84JtJ8BFDguSAikJUKGCHE0llbg7XRHqIMgxFb/OVAArbiwT0ZLk6vvcsqKLZ3u4kIp+2qXqf+/P1ecSckPR6xxqF9hKTSjFH72sBUjosY1nTF6+NeeN5IJQzsatGV1YCBJPGmgvLQ+ahStnn480+j0XVJbXLDi037uSEq55OE5eGq2HmyB1YjjLT2scqfIv0GyxM9RfrNl9zg9vRRafrSbI6CtORk/BXakiz7U1KvA3lqQErAqmM1i2vgaeoCvRny/xMjPaE2VJCO2ZlUOPeCYbSz+6UN0LzjG8V4pT2tQFEyANMOfJU753oKAv+Q2egP/sW2Bf2QUeIo1a/X7AVeIuDxuSOBKFJM6Ojt1R/o84QQELaotegcaxgvzzExtFE2jiV3Evt/m+3NDZ+szqIhb8ta/DAxI8Yg3q8ZyUb/lYebfwLgPBaIaCgGbA6yn+ovoFFjY47z8t7m21gh79uu11kotcQ5R24TNF5iAGYePNfSld6J9UtAISUHiB9djP5RlJylO/KgijRaq44jMEOU9sJSNdNrc=
  - secure: LkO/murOHo0ipDz4IKw0E6hYPpZGTcrRJx7oS1l5U3P2C6xG4pzi+qMReAp+gHL/0CVvfAmT60nCnzeEpegCIZNXfiaDdSo4Hg7zWkFOoH1MGqXjWuCjE1koyc8n1nl58v38WwPPvoyFWnE9Uy4m4yb1HndGmmMkrCW2WBotRiT+ZcLzbSowB3UoKaASJPwqDuQBUUH/ku0s4kiC1wznmmiJzfiyAuS5tLl4NqmWaLcOZ3sXoGzXw62OwEzW1oGzLMXWbq4t9HUu3/2XiLYuPG9ES6OAa7cbN2fiB2YdGpavcCqN8LU88+Hv3TlZIwuFOqMyGN7OSCcAk+74ZVsTPpzN8O6/pCSOCH9trclufLBlG5h76D8/Z4UGKIsqwxA+DrRLg2CLjXh8geSHnlFFA/CVg870JUox7RN8vXL4JgcyjtG+7gTpNavZ1/WXzun61sgSEYNukO6eTRnN6FZabSW8eKNSbrNk/UvMl/DgKar05mpTvFia8uq7ruw/adjunC5UuODJ5/PP18usTr0U5wJGSWhK7Ry8/mmUSL3nGVaA9hQAj5ob28j51FaSqWfbX069UuA8PMlELLuE9W05kfDqz6p8TTRatuDDKDo588xainZJzg78kz+2lHWPQJG6KMTDCQdZOqMynl+EARJKQ9Ikxi4eTLZb8bXszhcVzEY=
before_install:
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password" -in id_rsa.enc -out deploy_key -d; fi
after_success:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
