sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
after_success:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET"
  -in deploy.enc -out deploy_key -d; fi
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
env:
  global:
  - secure: jcX8V+I8FMZs6j/LPe0SGsp/RkwMK9uDyKp2XhcV2YQa678p5L4rR7YX8Ewi3kNNbrKeVVXsiHTrdmgFmqt0rcqMwXacrQYTa9FJTWyvOuv1BdjLZf484HNmLLGVH8lGo1cep3VVGp/EiTwLwq66QawjPqcx3iPzCxEh2hNaKbGOeV5d7JXyhaTz5MpbnCpYAUHO1fAe7L3VF6yWDOS3Yv40Na5uozWZUs4mm3FOD6029VwBqlnUzxbyLzwUvVrHqbq4AYFdWOSlRpOZT/SDRavwQEzkWVnMODbbA8TjAThgEGQXad+RwOo09UoqrRyTWgEhLBjzUEsYfMlPozd5n5Y01h9KE108YgyCFf+7nyHiuUUPsWVm5ywUZiV/Wnz9csT54FqyGj6wcj9fV/L4eVqTfKvfHXQmXo97ucVaW/q+GPDnKFQ/KIkl189YeLslJvKUnSuKnJSuLa5tam4Fi7hvmz+5a5JIc+Eb5CcCo0hhJVqwaru2bSi1GmM0dLk5G5c9mkoLHPfrA5+W6KbVmYvXXDNETX8b04e5nkNktEc462RJpXueQnCHWHllUtNTgmTt6EGqlWSNv2mUWtZU7pe3Tynw155/plYHJhV9/yuDR7nMR5wKW0e+4uvsE0t6I/o8puJzwyYVo8nGwwIScfC6eE8LIW0Gxc0rcppVli0=
  - secure: ONd3ktFDksSb4D3/VZ7M2/LwDZKdmLK6ZggdZSJQAZaFRI9XSR+wb/1iJwnniViO1vuEmBrr+FD1PsV+C+hLZJVevRg7SYYStSRzXLw4B4rsThCErUuGD1vVeQ0t9aYakCQSEKssijMpKu+yRIAE6jA+31OmqG0hWYmwON2aNMYk5plU6Wm5fOetp/P7BETRDifpWWvZqW4LQcTBMnLRPRxmgxXBW67CaxGGhgUaqSp/sVSF85PungzitYbfuC9/4VFTDSaP0pRZq8i4mjLeto6w+WK1ndz77Wz/s61Seqsh/ZInqXwIF5Z8NBZK+fUInwq5tninz0qXV4zpL0V4VbctwBSLIdn8nboncNVuB5tMfD/O++5MdeO+DNeg3rn9Fd/nT8Z52n8qckeTzTAq9t2+f+f5xjjPpz25Ex2UAvk+5ivyETCLgWRL1z4wSIAUqPdyR1L2DwUIy6p3IZPgCTx3kOkpXpW/ELlgvuf+JL477O7SUQoB42ysckNaVhBKnQYRSXsW6j9yepV5x7YbAz6bxI9vlqP4KeblrHmKEjirYy38fcZ4k7t1ajd2q3eU1INxcXor0rrAOzgFMvEv3JSDc9xCkoWSKSv9zff+ZMyZVPJucri7zfNSqZhrZLH7lzTMmHIGuUWHWcDRyzymgziKTE9N4vb3YvqMWeKHXpg=
